---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: snipeit
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_USER
              value: snipeit
            - name: MYSQL_PASSWORD
              value: snipepass
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snipeit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snipeit
  template:
    metadata:
      labels:
        app: snipeit
    spec:
      containers:
        - name: snipeit
          image: snipe/snipe-it
          ports:
            - containerPort: 80
          env:
            - name: APP_URL
              value: http://localhost:30080
            - name: APP_KEY
              value: "base64:Gx9z3A0Ht4v9sYq9K4t1aB4k6NHlT0ZpXKk3J6cYdG8="
            - name: DB_HOST
              value: mysql
            - name: DB_DATABASE
              value: snipeit
            - name: DB_USERNAME
              value: snipeit
            - name: DB_PASSWORD
              value: snipepass
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: snipeit-service
spec:
  type: NodePort
  selector:
    app: snipeit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080